language: python

python: 
    - "3.4"
    - "3.7"

install:
    - pip install -r requirements.txt
    - pip install pytest pytest-cov codecov

script:
    - pytest --cov=./


branches:
    only:
        - master

after_success: 
    - codecov
