dist: "bionic"
language: python

### JOBS THAT ARE ASSIGNED TO DEFAULT 'TEST' STAGE.

python:
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements_python.txt
  - pip install -r test/requirements_python.txt
script: pytest --cov=test/
after_success: codecov

### JOBS THAT ARE ASSIGNED TO 'Deploy' STAGE.

jobs:
  include:
    - stage: "Deploy"
      python: "3.7"
      os: "linux"
      install:
        - ./bin/install.sh
        - ./test/requirements_linux.sh
      before_script:
        - which pip
        - pip list
      script: bats ./test/test_deployment.sh

### EXTRA CONFIGURATION

notifications:
  email:
    recipients: oz.alikhan@gmail.com
    on_success: always
    on_failure: always
