language: python

python:
    - "3.6"
    - "3.7"

install:
    - pip install -r requirements.txt
    - pip install pytest pytest-cov codecov

script:
    - pytest --cov=./

after_success: 
    - codecov

notifications:
  email:
    recipients:
     - oz.alikhan@gmail.com
    on_success: always
    on_failure: always
