language: python

jobs:
  include:
    - stage: "Unit/Integration tests"
      python:
        - "3.6"
        - "3.7"
      install:
        - pip install -r requirements_python.txt
        - pip install -r install_python_requirements.txt
      script: pytest --cov
      after_success: codecov

notifications:
  email:
    recipients:
     - oz.alikhan@gmail.com
    on_success: always
    on_failure: always
