dist: "bionic"
language: python

### JOBS THAT ARE ASSIGNED TO DEFAULT 'TEST' STAGE.

#python:
#  - "3.6"
#  - "3.7"
#
#install:
#  - pip install -r requirements_python.txt
#  - pip install -r test/requirements_python.txt
#script: pytest --cov=test/
#after_success: codecov

### JOBS THAT ARE ASSIGNED TO 'Deploy' STAGE.

jobs:
  include:
    - stage: "Deploy"
      python: "3.7"
      os: "linux"
      before_install:
        - sudo apt-get update
      install:
        - sudo ./bin/install.sh
        - ./test/requirements_linux.sh
      before_script:
        - sudo chmod o+rx /home/travis
        - sudo su - root
        - su - aroundtheclock
        - cd /
        - cd /home
        - cd /home/travis
        - cd /home/travis/build /home/travis/build/OthmanEmpire
        - cd /home/travis/build/OthmanEmpire
        - cd /home/travis/build/OthmanEmpire/project_aroundtheclock
        - cd /home/travis/build/OthmanEmpire/project_aroundtheclock/bin
        - ./home/travis/build/OthmanEmpire/project_aroundtheclock/bin/run.sh &
      script:
        - bats ./test/test_deployment.sh
        - sudo systemctl -l status aroundtheclock.service
        - sudo journalctl -u aroundtheclock.service
        - ls -ld /
        - ls -ld /home
        - ls -ld /home/travis
        - ls -ld /home/travis/build /home/travis/build/OthmanEmpire
        - ls -ld /home/travis/build/OthmanEmpire
        - ls -ld /home/travis/build/OthmanEmpire/project_aroundtheclock
        - ls -ld /home/travis/build/OthmanEmpire/project_aroundtheclock/bin

### EXTRA CONFIGURATION

notifications:
  email:
    recipients: oz.alikhan@gmail.com
    on_success: always
    on_failure: always
