dist: "bionic"
language: python

### JOBS THAT ARE ASSIGNED TO DEFAULT 'TEST' STAGE.

#python:
#  - "3.6"
#  - "3.7"
#
#install:
#  - pip install -r requirements_python.txt
#  - pip install -r test/requirements_python.txt
#script: pytest --cov=test/
#after_success: codecov

### JOBS THAT ARE ASSIGNED TO 'Deploy' STAGE.

jobs:
  include:
    - stage: "Deploy"
      python: "3.7"
      os: "linux"
      before_install:
        - sudo apt-get update
      install:
        - sudo ./bin/install.sh
        - ./test/requirements_linux.sh
      before_script:
        - sudo chmod a+rwx /home/travis
        - sudo chmod -R a+rwx /home/travis/*
        - sudo chmod -R a+rwx /home/travis/.travis*
        - sudo chmod -R a+rwx /home/travis/{.profile,.bash*,.config}
        - sudo chmod a+rwx /home/travis/.erlang.cookie
        - sudo chmod a+rwx /home/travis/.viminfo
        - sudo chmod a+rwx /home/travis/.gemrc
        - sudo chmod a+rwx /home/travis/.gitconfig
        - sudo chmod a+rwx /home/travis/.my.cnf
        - sudo chmod a+rwx /home/travis/.mkshrc
        - sudo chmod a+rwx /home/travis/.zlogin
        - sudo chmod a+rwx /home/travis/.zshrc
        - sudo chmod a+rwx /home/travis/.rvmrc
        - sudo chmod a+rwx /home/travis/.bzr.log
        - sudo chmod a+rwx /home/travis/.travis_ci_environment.yml
        - sudo chmod a+rwx /home/travis/.bash_profile
        - sudo chmod a+rwx /home/travis/.bashrc
        - sudo chmod a+rwx /home/travis/.profile
        - sudo chmod a+rwx build/home/travis/.sh
        - sudo chmod a+rwx /home/travis/.travis_packer_templates_rspec.json
        - sudo chmod a+rwx -R /home/travis/.ssh
        - sudo chmod a+rwx -R /home/travis/.mozilla
        - sudo chmod a+rwx -R /home/travis/.gnupg
        - sudo chmod a+rwx -R /home/travis/.cache
        - sudo chmod a+rwx -R /home/travis/.m2
        - sudo chmod a+rwx -R /home/travis/.gimme
        - sudo chmod a+rwx -R /home/travis/.nvm
        - sudo chmod a+rwx -R /home/travis/.packer.d
        - sudo chmod a+rwx -R /home/travis/.bazaar
        - sudo chmod a+rwx -R /home/travis/.ccache
        - sudo chmod a+rwx -R /home/travis/.gem
        - sudo chmod a+rwx -R /home/travis/.local
        - sudo chmod a+rwx -R /home/travis/.lein
        - sudo chmod a+rwx -R /home/travis/.subversion
        - sudo chmod a+rwx -R /home/travis/.npm
        - sudo chmod a+rwx -R /home/travis/.phpenv
        - sudo chmod a+rwx -R /home/travis/.rvm
        - sudo chmod a+rwx -R /home/travis/.yarn
        - sudo chmod a+rwx -R home/travis/bin
        - sudo chmod a+rwx -R home/travis/builds
        - sudo chmod a+rwx -R /home/travis/.bash_profile.d
        - sudo chmod a+rwx -R /home/travis/.travis
        - sudo chmod a+rwx -R /home/travisgopath
        - sudo chmod a+rwx -R /home/travisperl5
        - sudo chmod a+rwx -R /home/travisbats
        - sudo chmod a+rwx -R /home/travisbuild
        - sudo chmod a+rwx -R /home/travis/.config
        - sudo chmod a+rwx -R /home/travis/virtualenv
        - sudo chmod a+rwx -R /home/travis/.bash_logout
        - sudo ls -la /home/travis
      script:
        - bats ./test/test_deployment.sh
        - sudo systemctl -l status aroundtheclock.service
        - sudo journalctl -u aroundtheclock.service
        - namei -mo /home/travis/build/OthmanEmpire/project_aroundtheclock/bin

### EXTRA CONFIGURATION

notifications:
  email:
    recipients: oz.alikhan@gmail.com
    on_success: always
    on_failure: always
