language: python

jobs:
  include:
  - stage: "Unit/Integration Tests"
    python:
      - "3.6"
      - "3.7"
    os: "linux"
    install:
      - pip install -r requirements_python.txt
      - pip install -r test/requirements_test_python.txt
    script: pytest --cov=test/
    after_success: codecov

  - stage: "Deployment"
    python:
      - "3.6"
      - "3.7"
    os: "linux"
    install:
      - ./bin/install.sh
      - ./test/requirements_test_linux.sh
    before_script:
      - chmod u+x bin/install.sh
      - chmod u+x test/requirements_test_linux.sh
      - chmod u+x test/test_deployment.sh
    script: ./test/test_deployment.sh

notifications:
  email:
    recipients: oz.alikhan@gmail.com
    on_success: always
    on_failure: always
