language: python


matrix:
  include:
  - stage: "Source code testing"
    python: "3.6"
    install:
      - pip install -r requirements_python.txt
      - pip install -r test/requirements_test_python.txt
    script: pytest --cov
    after_success: codecov

  - stage: "Deployment"
    before_install:
      - chmod +x bin/install.sh
      - chmod +x test/requirements_test_linux.sh
      - chmod +x test/test_deployment.sh
    install:
      - ./bin/install.sh
      - ./test/requirements_test_linux.sh
    script: ./test/test_deployment.sh

notifications:
  email:
    recipients:
     - oz.alikhan@gmail.com
    on_success: always
    on_failure: always
