dist: "bionic"
language: python

### JOBS THAT ARE ASSIGNED TO DEFAULT 'TEST' STAGE.

#python:
#  - "3.6"
#  - "3.7"
#
#install:
#  - pip install -r requirements_python.txt
#  - pip install -r test/requirements_python.txt
#script: pytest --cov=test/
#after_success: codecov

### JOBS THAT ARE ASSIGNED TO 'Deploy' STAGE.

jobs:
  include:
    - stage: "Deploy"
      python: "3.7"
      os: "linux"
      before_install:
        - sudo apt-get update
      install:
        - sudo ./bin/install.sh
        - ./test/requirements_linux.sh
      before_script:
        - sudo ls -la /home/travis

       sudo chmod a+rwx /home/
        - sudo chmod a+rwx /home/travis
        - sudo chmod -R a+rwx /home/travis/.travis*
        - sudo chmod a+rwx /home/travis/.bash_profile
        - sudo chmod a+rwx -R /home/travis/.bash_profile.d
        - sudo chmod a+rwx /home/travis/.bashrc
        - sudo chmod a+rwx /home/travis/.gitconfig
        - sudo chmod a+rwx /home/travis/.my.cnf
        - sudo chmod a+rwx /home/travis/.profile
        - sudo chmod a+rwx /home/travis/build.sh
        - sudo chmod a+rwx -R /home/travis/.cache
        - sudo chmod a+rwx -R /home/travis/.local
        - sudo chmod a+rwx -R /home/travis/bin
        - sudo chmod a+rwx -R /home/travis/builds
        - sudo chmod a+rwx -R /home/travis/bats
        - sudo chmod a+rwx -R /home/travis/build
        - sudo chmod a+rwx -R /home/travis/.config
        - sudo chmod a+rwx -R /home/travis/virtualenv
        - sudo ls -la /home/travis
      script:
        - bats ./test/test_deployment.sh
        - sudo systemctl -l status aroundtheclock.service
        - sudo journalctl -u aroundtheclock.service
        - namei -mo /home/travis/build/OthmanEmpire/project_aroundtheclock/bin

### EXTRA CONFIGURATION

notifications:
  email:
    recipients: oz.alikhan@gmail.com
    on_success: always
    on_failure: always
