language: python

jobs:
  include:
    - stage: "Unit/Integration tests"
      matrix:
        include:
          python:
            - "3.6"
            - "3.7"
      install:
        - pip install -r requirements_python.txt
        - pip install -r test/requirements_test_python.txt
      script: pytest --cov
      after_success: codecov
    - stage: "Deployment"
      install:
        - chmod u+x ./bin/install.sh && ./bin/install.sh
        - ./test/install_linux_requirements.sh
      script: ./test/test_deployment.sh

notifications:
  email:
    recipients:
     - oz.alikhan@gmail.com
    on_success: always
    on_failure: always
