language: python

python: 
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"

install:
    - pip install -r requirements.txt
    - pip install pytest pytest-cov

script:
    - pytest --cov=./


branches:
    only:
        - master

after_success: 
    - codecov --file coverage/lcov.info --disable search
